### ISSUE TITLE
Routes from TreeRouterStack supplied in contructor are ignored since 1.3

### ISSUE THREAD

**Issue by Articus** [zendframework/zend-expressive-zendrouter#18]
I just wanted to ask if the following usage is allowed:
```PHP
$config = [
	'routes' => [
		'test' => [
			'type' => 'Literal', 
			'options' => [
				'route' => '/test',
			]
		]
	],
	'default_params' => [
		'middleware' => 'MyMiddleware',
	],
];

$treeRouter =\Zend\Router\Http\TreeRouteStack::factory($config);
$zendRouter = new \Zend\Expressive\Router\ZendRouter($treeRouter);
$zendRouter->match(/*request to /test */);
```
Before 1.3 it was working fine, but since 1.3 route matching does not work because Zend\Expressive\Router\ZendRouter::addRoute is not called and [this line](https://github.com/zendframework/zend-expressive-zendrouter/blob/master/src/ZendRouter.php#L164) returns null. And that is a shame because it was reallly convinient to use tree-like configuration via simple custom factory :( .

**Comment by weierophinney** [comment]
That was never a scenario we explicitly supported, and will not work with zend-expressive-router 2.0 (which version 1.3 of this package now depends on), as that version requires building a `RouteResult` from a `Zend\Expressive\Router\Route` instance — which is what the code you linked to retrieves in order to return the result.

(Generally speaking, what you're doing will also impact `generateUri()`, as that method *also* depends on routes being injected via `addRoute()` and not as you have done.)

If you want to allow the above, you would need to extend the router and override the `match()` method to check for a `Route` instance, and, if not found, use the information from the zend-router `RouteMatch` to create one for use in creation of a `RouteResult`.
