### ISSUE TITLE
zend-expressive-zendrouter and optional parameter in view url helper

### ISSUE THREAD

**Issue by Sohorev** [zendframework/zend-expressive-zendrouter#21]
If you have time to check the operation of the optional parameters together with the form view URL helper. I have not earned the optional parameters. I can not provide additional information as I switched to fast-route

**Comment by weierophinney** [comment]
@Sohorev You'll need to provide us far more information than you have for us to do anything. Answers to the following questions:

- What were you trying to do?
- What did you expect to happen?
- What actually happened?

are needed at the minimum. Ideally, since this deals with routing and URI generation, you can also demonstrate a little bit of configuration with regards to routes.

**Comment by Sohorev** [comment]
I have a following route config:
```
            'routes' => [
                [
                    'name' => 'user.edit',
                    'path' => '/user/edit[/:id]',
                    'middleware' => Controller\EditController::class,
                    'allowed_methods' => ['GET', 'POST'],
                ],
            ],
```

In my view I have code:

`<a href="<?php echo $this->url('user.edit')?>">add</a>`
It generate exception:  Zend\Router\Exception\InvalidArgumentException Missing parameter "id"

But this code work normaly:
`<a href="<?php echo $this->url('user.edit', ['id' => 1])?>">edit</a>`

**Comment by weierophinney** [comment]
This is out of the purview of the router implementation, and is something that we have implemented in [zend-expressive-helpers](https://github.com/zendframework/zend-expressive-helpers) via its `UrlHelper` implementation, which is also incorporated into the various template implementations.

The reason for this is because we cannot track what the last matched route was in the various router implementations; that's tracked via the `RouteResult` instance _returned_ on a successful match, but that value object is not _stored_ in the router itself, in order to allow the router to remain stateless.

Use the `UrlHelper` as noted above if you need the behavior you detail above, as it incorporates that.
