### ISSUE TITLE
The Zend Router cannot have routes directly added

### ISSUE THREAD

**Issue by dmnc** [zendframework/zend-expressive-zendrouter#24]
This seems to be because of the following change:

https://github.com/zendframework/zend-expressive-zendrouter/pull/12/files#diff-4c16e0300398ea4465dac55ba5fcade3L149

The condition that should never happen is indeed happening for me. This is because `$this->routes` is empty as all my routes are defined in the injected `Zend\Router\Http\TreeRouteStack`.

Previously, the result was created from the match and didn't require a route (or middleware).

I'm not sure if I was potentially using this package incorrectly before and it was working by accident.  It was very useful when migrating a legacy application that has all its routes defined using the zend style calls.

**Comment by weierophinney** [comment]
The change presented there is to ensure that the router implementation works the same as all other implementations with regards to how the route result is populated. Without a `Zend\Expressive\Router\Route` instance, the route result cannot be populated correctly, and we will have no ability to determine how OPTIONS and HEAD requests should be handled.

We never specifically supported the idea of populating the `TreeRouteStack` directly, due in part to the fact that we needed to be able to determine the methods supported, as well as be able to generate URIs based on route, and each of those required a `Zend\Expressive\Router\Route` instance. The fact that you _could_ populate the `TreeRouteStack` independently was a side effect, and never intentional.

I would suggest creating a bridge that would create those `Route` instances from configuration when possible. That said, we only support `Segment` routes currently, which means you might need to do additional work to make things happen.

Alternately, you could pin to an earlier version of zend-expressive-zendrouter until your migration is complete.

**Comment by dmnc** [comment]
Thanks for the speedy reply. I suspected this might be the case.

As you rightly point out, the issue with a bridge is not supporting the more complex route types, regex being a particular sticking point for us (as raised in #22).

I'm not quite sure how generating URIs from routes is related, as the interface currently does it from the route name which goes straight through to the underlying Zend router's assemble method.

Would you consider making the methods in `Zend\Expressive\Router\ZendRouter` protected rather than private? That would allow me to extend the class and tweak `marshalSuccessResultFromRouteMatch` to generate `Zend\Expressive\Router\Route` instances on the fly.

**Comment by weierophinney** [comment]
@dmnc Send over a PR requesting the change, with some detail about what it will enable, and I'll review for a new release.

Thanks!
